language: julia
os:
  - linux
  - osx
julia:
  - 0.5
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Hermetic"); Pkg.test("Hermetic"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Hermetic")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
